#!/usr/bin/env bash

set -euo pipefail

PYTHON_BIN="${PIP_PYTHON:-python3}"

"${PYTHON_BIN}" -m pip \
    install \
    --upgrade \
    --disable-pip-version-check \
    --constraint constraints.txt \
    "${@}"
