#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

if [ ! -d .venv ]; then
    python3 -m venv .venv
fi

export PIP_PYTHON="$(pwd)/.venv/bin/python"

scripts/install/pip_packages "pip<23.2,>=21.3.1"
scripts/install/pip_packages setuptools wheel
scripts/install/pip_packages \
    --requirement requirements_dev.txt \
    --requirement requirements_base.txt \
    --requirement requirements_lint.txt
